color: teal
fieldLayouts:
  0d111b95-990c-4471-b878-97386e513d59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b2f8159f-d073-4dca-9b95-b397793e73fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ad46406-1b63-42da-b3d7-2f3936331af1 # NavName
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50145361-0346-4f9f-853f-2c252b545d25
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce9a36a4-651b-4d25-a63b-55276cab1b25 # urlLinks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ae9d285-b3ea-4014-b7f0-36fc75f8a0c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 86ad7c2c-9570-46cb-b094-9205fa58df6d
        userCondition: null
handle: navigationItem
hasTitleField: true
icon: bars
name: 'Navigation Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
