color: null
fieldLayouts:
  51bb5b4d-57a5-47f0-a0b1-2fb3e1b5c8f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c353c1a6-c18e-41c1-be46-f8bf2342b32b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: efe5d865-7c61-4ff8-9102-6aebeed0423d # minPrijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14182d97-5391-4cf5-918a-c83b2baf8191
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54c53414-b415-4b62-9c17-34d8ee322c23 # maxPrijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1299a6c6-70e2-48f9-a05d-0e94c2de5579
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61636f38-891f-47ad-97d2-fba1d3ad6484
        userCondition: null
handle: prijscategorie
hasTitleField: true
icon: ''
name: Prijscategorie
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
