color: lime
fieldLayouts:
  76da80b2-fbae-4f81-a627-30afd890aa9c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c7c4e5b5-87c4-45b9-916f-6485bb88823b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d9e1da80-19c5-4e29-a0f4-175f8e05720b # blockProducts
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec4cb05f-2dc1-4171-8776-394caefc2978
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50578578-3882-4f42-b8a4-9a8bea85a3cf
        userCondition: null
handle: productsblock
hasTitleField: true
icon: bag-shopping
name: ProductsBlock
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
