color: null
fieldLayouts:
  100a4e9a-843a-4c72-b389-07f3808748bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 43e8436d-bce1-41c4-8644-2e31b731b121
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7028ecad-3014-43e2-b223-a872366b97d6 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ce1e5c1-4ded-4055-a3a7-016f9ce06fa4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1228e474-80b9-4037-ac06-e7eb9cdc5d7d # MerkEntries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 039c20e1-9c4d-4e54-a7f8-376d3464d97d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 10265da2-3614-4f52-b829-951e050c6630
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28da4615-b03a-44b6-8f5a-07e7de7d5b80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 503551c3-729b-4630-a072-c1121d331485 # Soort
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c25749aa-bc71-4e34-b1e0-867d1d9960fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6fcea98-619b-48a3-a423-6091162e0b38 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e467574-6736-445e-ac8e-c74e6c87c2aa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee419d88-11a8-4bdd-ad75-63badd6cf7c0 # Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffc4a840-9720-4e4d-8975-0f2fba4c126c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d175920a-2bd8-4fe4-8ddd-19635c38a533 # Voorraad
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5652917-52bb-45d1-a11f-28d211b19ffb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 558c8426-0c72-4ae9-b8d0-b0b70909d1e6
        userCondition: null
handle: productentry
hasTitleField: true
icon: basket-shopping
name: ProductEntry
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
