color: fuchsia
fieldLayouts:
  d9b547ab-d7a7-486a-8b7d-1adf23a24e0d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f180ef0-2920-41fb-a1ca-d81bbfe8253c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 06c67e2e-d236-4a42-a3eb-053b87b2ab82
        userCondition: null
handle: startpagina
hasTitleField: true
icon: house
name: Startpagina
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
