color: orange
fieldLayouts:
  0cc463fd-0576-4161-9a52-08e89aeef45d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 09832b4d-7341-446c-ba73-8c4e92e10876
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4db4e5e8-bf47-4751-bbd0-cf8b7268ab06 # blockTitel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 570a9f40-dfdd-4f34-a0a8-2507637858a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6dabdd55-7158-4ea2-928a-dc474961536f # blockImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0d9e926-4a96-4f3b-afa1-23f8c39aa611
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d99c1100-6901-4bbe-9b45-5d1e8ba04abc # blockTekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 365d5383-5c8e-4e47-9f27-6cd1c78dafdc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e513a234-130a-4816-ba95-b085d9a5086d # positionImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ce98cc6-e3ad-4008-8204-1cb4b7df5947
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2cb1ba17-6d29-4ea5-87fb-e9cc85866e48
        userCondition: null
handle: textimgblock
hasTitleField: true
icon: brackets-curly
name: TextImgBlock
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
