altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c2f2b73f-7a44-45b3-b464-7b37bd46e46b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fdffc592-9ff9-487d-a025-fb29d03e3090
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6dabdd55-7158-4ea2-928a-dc474961536f # blockImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec1d3a56-3c3c-4c93-ac56-1e8a8f30846d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ab1086f-a387-493d-8dd3-372c7a6b7252
        userCondition: null
fs: blockimage
handle: blockimage
name: blockImage
sortOrder: 6
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: blockimage
transformSubpath: ''
