altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ad41d11e-5517-4edc-8d60-eef257134401:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c41cc2f3-7ea0-4364-bef4-97545f566191
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7028ecad-3014-43e2-b223-a872366b97d6 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f30875c5-c21b-48e8-87c8-26f41fa97835
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 034a0410-c6d5-4b9b-99d2-a288d4fe1ca7
        userCondition: null
fs: productimg
handle: productimg
name: productImg
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
