altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  738e8638-c534-42c9-b572-5a89c0ebec7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7331cb0c-7b5e-488f-9bc0-5b9eab8fb72d # siteLogo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf37df30-470d-4a54-90b4-a6419c48632e
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 411c72d7-1099-4200-a8cc-a4fa75c1ff5b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5bd75ba6-47cf-4a04-b5fa-bb443f895fb8
        userCondition: null
fs: sitelogo
handle: sitelogo
name: SiteLogo
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: sitelogo
transformSubpath: ''
