columnSuffix: null
handle: blocktitel
instructions: 'Dit is de titel boven je blok'
name: blockTitel
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
