columnSuffix: null
handle: footerContent
instructions: 'Hierin steek je de content van je footer'
name: 'Footer Content'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
