columnSuffix: null
handle: headerContent
instructions: 'Hierin steek je de contents van je navigatiebalk'
name: 'Header Content'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
