columnSuffix: null
handle: infodescription
instructions: 'dit is eenbeschrijving van het stukje info'
name: infoDescription
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
