columnSuffix: null
handle: merk
instructions: 'Geef hier het merk van het product in'
name: Merk
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Product Name'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
