columnSuffix: null
handle: soort
instructions: 'Hierin geef je de naam van het product'
name: Soort
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: 'Product naam'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
