columnSuffix: null
handle: voorraad
instructions: 'Hierin geef je of het product op voorraad is of niet'
name: Voorraad
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
