dateModified: 1715884501
email:
  fromEmail: beyza.cevik@student.pxl.be
  fromName: kserenity-skincare
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7efebcfe-cbe8-4d2a-a4c0-c75c069d028e: kserenity-skincare # kserenity-skincare
    30863589-1efd-4876-8616-a9940a064ced: kserenity-skincare # kserenity-skincare
system:
  edition: solo
  live: true
  name: kserenity-skincare
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
