dateModified: 1716730875
email:
  fromEmail: beyza.cevik@student.pxl.be
  fromName: kserenity-skincare
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  blacklogo:
    hasUrls: true
    name: blackLogo
    settings:
      path: /assets/SVG/SVG
    type: craft\fs\Local
    url: '@web/assets/SVG/SVG/'
  blockimage:
    hasUrls: true
    name: blockImage
    settings:
      path: /assets
    type: craft\fs\Local
    url: '@web/assets/'
  contactimg:
    hasUrls: true
    name: ContactImg
    settings:
      path: /assets/svg/svg
    type: craft\fs\Local
    url: '@web/assets/svg/svg'
  productimg:
    hasUrls: true
    name: productImg
    settings:
      path: /assets
    type: craft\fs\Local
    url: '@web/assets/'
  sitelogo:
    hasUrls: true
    name: SiteLogo
    settings:
      path: /assets/SVG
    type: craft\fs\Local
    url: '@web/assets/SVG/'
meta:
  __names__:
    0e4ebf1a-a242-45fb-9206-cad3057ccbc4: contactTel # contactTel
    0e72854b-8c3b-4835-8c77-2bad29d28ea8: contactTitleSocials # contactTitleSocials
    1ad46406-1b63-42da-b3d7-2f3936331af1: NavName # NavName
    4db4e5e8-bf47-4751-bbd0-cf8b7268ab06: blockTitel # blockTitel
    4fb85cd4-efac-460c-8f5b-5ff376849212: MerkType # MerkType
    6beb16d9-e71f-4fb5-826a-c52b6a7a8857: ProductenTitle # ProductenTitle
    6dabdd55-7158-4ea2-928a-dc474961536f: blockImage # blockImage
    7cb8b0db-c230-471d-bd63-642a532fc6de: ContactImg # ContactImg
    7dcb02f2-e42e-4938-b65a-c23f9090601b: contactTitleMail # contactTitleMail
    7e8c3b95-aa54-49c0-94da-65851b734c98: 'Content Blocks' # Content Blocks
    7e83d19b-9f19-4664-a036-9ed99d691b97: 'Public Schema' # Public Schema
    7efebcfe-cbe8-4d2a-a4c0-c75c069d028e: kserenity-skincare # kserenity-skincare
    7f274b1f-e75a-4482-b11b-fb766655c7f8: contactTitleTel # contactTitleTel
    8e390fb5-107f-4750-8975-6438c74df7b7: 'Custom Content Blocks' # Custom Content Blocks
    9a77c145-c53b-44a4-bdb2-2dc307052d32: blackLogo # blackLogo
    9ac71a7d-eac6-4b5a-bb77-2f40d6e5ae95: homepageDescription # homepageDescription
    9f0a7f3f-bace-4561-8976-d096dfd5f841: ProductsBlock # ProductsBlock
    32ec3ad3-e3ec-488b-9670-185dcae1a236: Header # Header
    48f60c35-6b15-498e-85e5-ea8d92527c3c: Homepage # Homepage
    49dd7690-de8b-4c4c-acf6-ea0bed781c88: contactMail # contactMail
    57c5864f-39e3-4d02-b5da-84682a68b4ff: ProductenMatrix # ProductenMatrix
    78e6d6aa-2364-4bf6-9bf8-b2e4fbe22ea1: blockImage # blockImage
    87afe98a-c5a0-4ac8-a3b6-6bd2c48da0c5: 'Homepage Entry' # Homepage Entry
    259b293c-e5d6-482f-98e8-158a8a0f6b88: ProductenPage # ProductenPage
    685d1f25-9518-4ae0-af58-7792cf56ee2b: homepageButtonText # homepageButtonText
    723be697-4f69-4566-9a16-46be763d8156: ContactTitle # ContactTitle
    1228e474-80b9-4037-ac06-e7eb9cdc5d7d: MerkEntries # MerkEntries
    4949eae4-4151-4200-969e-16fb4e858353: contactEntry # contactEntry
    6674a1a0-2dfe-4f5d-8551-b4cc53faf7e6: TextBlock # TextBlock
    7028ecad-3014-43e2-b223-a872366b97d6: Image # Image
    7331cb0c-7b5e-488f-9bc0-5b9eab8fb72d: siteLogo # siteLogo
    9971f49b-6318-4be1-af82-ffccc357c3e5: Footer # Footer
    29685f3e-1f14-43ff-90f4-cd1b385b8501: SiteLogo # SiteLogo
    30686f11-9053-4dae-8f96-cb51f32747a6: 'Main Navigation' # Main Navigation
    50710bb5-f101-45c9-a9ee-7d7d6ee91177: TextImgBlock # TextImgBlock
    55753d0c-0fda-4412-a22d-75868cdabef0: ContactFormulier # ContactFormulier
    65305b29-a1b4-4736-8ef8-a757decd3de9: ProductEntry # ProductEntry
    503551c3-729b-4630-a072-c1121d331485: Soort # Soort
    733460cf-826b-4bcf-8bec-56b6e807e10e: navigationItems # navigationItems
    09198301-3e1d-45c3-9125-88769e8fff27: ProductenDescription # ProductenDescription
    30863589-1efd-4876-8616-a9940a064ced: kserenity-skincare # kserenity-skincare
    99231847-01ad-49a3-9f72-28748387cf90: ImageBlock # ImageBlock
    a1c71d26-edbe-4486-8839-4c1e39426221: ContactBlock # ContactBlock
    a2a38407-09ac-4efb-8029-5a2effc4b312: 'Footer Content' # Footer Content
    a6fcea98-619b-48a3-a423-6091162e0b38: Description # Description
    aa18b816-e7a6-4e90-94ca-6cae62db99e9: productImg # productImg
    af083550-14b3-4f68-b5f9-cf8385bc1def: 'Header Content' # Header Content
    b1cb8570-0af8-49f4-a072-b31cfe735988: homepageTitle # homepageTitle
    b3d2304b-f423-490c-a5c9-719f9bfcc2e8: Merk # Merk
    b57b1002-f8d0-4634-b367-e7014e73cc8b: Products # Products
    b604aca1-59d4-4e78-883d-b5ac1d8bee64: topTitle # topTitle
    be983836-6554-4519-b171-a0260905f6a6: FormTitle # FormTitle
    c1301a7d-dc92-494c-ba91-175a1a8e411f: ContactImg # ContactImg
    cc336e9f-0b95-477b-8228-f511d15140f2: infoDescription # infoDescription
    cdaa359a-7a01-46a9-a621-786da92af95a: 'Contact Form' # Contact Form
    ce9a36a4-651b-4d25-a63b-55276cab1b25: urlLinks # urlLinks
    d9e1da80-19c5-4e29-a0f4-175f8e05720b: blockProducts # blockProducts
    d99c1100-6901-4bbe-9b45-5d1e8ba04abc: blockTekst # blockTekst
    d2572f0c-cf70-42cc-b297-2f25a7076fa6: blackLogo # blackLogo
    d175920a-2bd8-4fe4-8ddd-19635c38a533: Voorraad # Voorraad
    d2930100-335c-47ed-9934-ca2c76e54f16: homepageButtonLink # homepageButtonLink
    dacfeb3b-6ffa-416d-94ee-2587a3223cef: Contact # Contact
    e5cc458e-91ec-4257-a1f1-d20c8aa00a8b: ContactMatrix # ContactMatrix
    e55d4be9-a010-4072-b605-170ec7dcc2f0: infoTitle # infoTitle
    e513a234-130a-4816-ba95-b085d9a5086d: positionImage # positionImage
    eaa75001-0e4d-4b1a-815c-a7b10cd383a0: 'Custom Pages' # Custom Pages
    ec962417-3322-4da5-a5ad-df1967228a86: BlackLogo # BlackLogo
    ee419d88-11a8-4bdd-ad75-63badd6cf7c0: Price # Price
    f35a1087-1bdc-4c52-beb4-47b65b821e6c: New # New
    f4754e19-e308-44d8-97ed-912301c9df61: Merken # Merken
    f8145be8-29f8-43ae-b178-99d5f61d0b6c: Footer # Footer
    f2746321-ef1e-4494-a19b-998823890d27: FormDescription # FormDescription
    fa2f48b7-41a7-479d-892e-cfcb3bf5409d: 'Navigation Item' # Navigation Item
plugins:
  cookie-consent:
    edition: standard
    enabled: true
    licenseKey: OONYD9QY0DN5M85BSTUXPO2U
    schemaVersion: 1.5.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: D7QBSLHITXUVBKFQVYMRAURW
    schemaVersion: 3.4.4
  navigate:
    edition: standard
    enabled: false
    licenseKey: EEL1ZIP396LGY5THG0678PJO
    schemaVersion: 2.4.0
system:
  edition: solo
  live: true
  name: kserenity-skincare
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
