defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4949eae4-4151-4200-969e-16fb4e858353 # contactEntry
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  30863589-1efd-4876-8616-a9940a064ced: # kserenity-skincare
    enabledByDefault: true
    hasUrls: true
    template: contact.twig
    uriFormat: contact
type: single
