defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7e8c3b95-aa54-49c0-94da-65851b734c98 # Content Blocks
handle: custompages
maxAuthors: 1
name: 'Custom Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  30863589-1efd-4876-8616-a9940a064ced: # kserenity-skincare
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
