defaultPlacement: end
enableVersioning: true
entryTypes:
  - 65305b29-a1b4-4736-8ef8-a757decd3de9 # ProductEntry
  - 259b293c-e5d6-482f-98e8-158a8a0f6b88 # ProductenPage
handle: products
maxAuthors: 1
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  30863589-1efd-4876-8616-a9940a064ced: # kserenity-skincare
    enabledByDefault: true
    hasUrls: true
    template: product.twig
    uriFormat: 'products/{slug}'
type: channel
